---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: 'https://kubescape.github.io/helm-charts/'
    targetRevision: 1.17.3
    chart: kubescape-operator
    helm:
      values: |
        clusterName: kubescape-secret
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubescape
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
