---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
    kubefirst.konstruct.io/application-name: grafana
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.3.9
    helm:
      releaseName: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
