---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-kafka
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: kafka
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kafka
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 29.3.6
    helm:
      releaseName: my-kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
