---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-yourls
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: yourls
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: yourls
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: yourls
    repoURL: https://charts.yourls.org
    targetRevision: 5.7.5
    helm:
      releaseName: yourls
      values: |
        yourls:
          domain: yourls.<DOMAIN_NAME>
      ### Uncomment, move at the same level as `domain` and set the username & password (in the future, it will be added as secrets and not as clear values inside the YAML)
      # username: NEED-TO-BE-SET
      # password: NEED-TO-BE-SET
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
