apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: '1'
  name: flappy-kray
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
    - host: flappy-kray.<DOMAIN_NAME>
      http:
        paths:
          - backend:
              service:
                name: flappy-kray
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - flappy-kray.<DOMAIN_NAME>
      secretName: flappy-kray-tls
