---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_URL>
    path: <REGISTRY_PATH>/components/grafana
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
