---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-mysql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mysql
    name: <CLUSTER_DESTINATION>
  project: default
  source:
    chart: mysql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.19.1
    helm:
      releaseName: my-mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
