apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testkube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: testkube
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: testkube
    repoURL: https://kubeshop.github.io/helm-charts
    targetRevision: 1.11.214
    helm:
      releaseName: testkube
      # values: |
      #   example: value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true