---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-kubedoom
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: kubedoom
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubedoom
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: kubedoom
    repoURL: https://charts.christianhuth.de
    targetRevision: 1.0.0
    helm:
      releaseName: my-release
      values: |
        kubedoom:
          namespace: "development"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
