---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedoom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubedoom
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: kubedoom
    repoURL: https://christianknell.github.io/helm-charts
    targetRevision: 1.0.0
    helm:
      releaseName: my-release
      values: |
        kubedoom:
          namespace: "development"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
