apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  labels:
    app: crossplane-provider-terraform
  name: terraform-config
spec:
  args:
  - -d
  - --poll=2m
  envFrom:
  - secretRef:
      name: crossplane-secrets
