---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-datadog
  namespace: argocd
  annotations:
    kubefirst.konstruct.io/application-name: datadog-agent
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datadog
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: datadog
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.57.3
    helm:
      releaseName: datadog
      values: |
        datadog:
          apiKeyExistingSecret: datadog-secret
          clusterName: "<CLUSTER_NAME>"
          env:
          - name: DD_ENV
            value: "<CLUSTER_NAME>"
          logs:
            enabled: true
            containerCollectAll: true
          ### NOTE: uncomment to turn on datadog apm - you will also need the apm service uncommented below
          # apm:
          #   enabled: true
          # ### NOTE: uncomment to turn on network monitoring
          # networkMonitoring:
          #   enabled: true
          # ### NOTE: uncomment to turn on the process agent
          # processAgent:
          #   enabled: true
          #   processCollection: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# NOTE: uncomment below to establish a datadog apm service for your cluster to leverage
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: datadog-apm
#   namespace: datadog
# spec:
#   selector:
#     app: datadog
#   ports:
#     - protocol: TCP
#       port: 8126
#       targetPort: 8126
