---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <CLUSTER_NAME>-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
    kubefirst.konstruct.io/application-name: metrics-server
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: <PROJECT>
  source:
    repoURL: 'https://kubernetes-sigs.github.io/metrics-server'
    targetRevision: 3.12.0
    chart: metrics-server
    # It's not suggested to run in production with this parameter: you should deploy a signed certificate for kubelet instead
    helm:
      values: |
        args:
          - --kubelet-insecure-tls
  destination:
    name: <CLUSTER_DESTINATION>
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
