---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracetest-<ENVIRONMENT>
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tracetest
    name: <CLUSTER_DESTINATION>
  project: <PROJECT>
  source:
    chart: tracetest
    repoURL: https://kubeshop.github.io/helm-charts
    targetRevision: 0.2.55
    helm:
      releaseName: tracetest
      # values: |
      #   example: value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
